'\" t

.TH "BIN_SEARCH" "1" "22\ \&NOVEMBER\ \&2020" "BIN_SEARCH 1.0.0" "Mini number game"

.SH "NAME"
bin_search - number guessing mini game
.SH "SYNOPSIS"
\fBbin_search\fR [\fB--help\fR \fB-h\fR]
\fBbin_search\fR [\fB--roman\fR \fB-r\fR]
.SH "DESCRIPTION"
\fBbin_search\fR it is a guessing mini game where you choose a number from 1 to 100 and the program finds it whis bin search.
.SH "OPTIONS"
\fB--help -h\fR
.RS 4
Show help
.RE
.PP
\fB--roman -r\fR
.RS 4
Show roman number
.RE
.SH "AUTHORS"
Lev Smirnov